title: Drawer Quick Links
handle: drawer_quick_links
status: ready
variants:
  - name: default open
    status: 'ready'
    context:
      drawers:
        - index: 1
          title: 'November 8, 2016: General Election'
          links:
            - name: Pay a parking ticket
              theme: w
            - name: Pay a parking ticket
              theme: w
            - name: Pay a parking ticket
              theme: w
            - name: Pay a parking ticket
              theme: w
          open: true
        - index: 2
          title: 'November 8, 2016: General Election'
          subtitle: 'Last updated: 2/2017'
          links:
            - name: Pay a parking ticket
              theme: w
            - name: Pay a parking ticket
              theme: w
            - name: Pay a parking ticket
              theme: w
            - name: Pay a parking ticket
              theme: w
  - name: JS Controlled
    context:
      drawers:
        - title: 'November 8, 20 16: General Election'
          subtitle: 'Last updated: 2/2017'
          js: true
          variant: 'dr-ql--open'
          links:
            - name: Pay a parking ticket
              theme: w
context:
  drawers:
    - index: 1
      title: 'November 8, 2016: General Election'
      subtitle: 'Last updated: 2/2017'
      date: false
      open: true
      links:
        - name: Pay a parking ticket
          theme: w
        - name: Pay a parking ticket
          theme: w
        - name: Pay a parking ticket
          theme: w
        - name: Pay a parking ticket
          theme: w