title: Drawer Quick Links
handle: drawer_quick_links
status: ready
variants:
  - name: Hub
    preview: '@hub'
  - name: Mini
    context:
      drawers:
        - title: 'Filter by title'
          variant: 'dr-ql--sm'
          theme: b
          links:
            - name: Pay a parking ticket
              theme: w
            - name: Pay a parking ticket
              theme: w
            - name: Pay a parking ticket
              theme: w
  - name: JS Controlled
    context:
      drawers:
        - title: 'November 8, 2016: General Election'
          subtitle: 'Last updated: 2/2017'
          js: true
        - title: 'November 8, 20 16: General Election'
          subtitle: 'Last updated: 2/2017'
          js: true
          variant: 'dr-ql--open'
          theme: b
          links:
            - name: Pay a parking ticket
              theme: w
context:
  drawers:
    - index: 1
      title: 'November 8, 2016: General Election'
      subtitle: 'Last updated: 2/2017'
      date: false
      links:
        - name: Pay a parking ticket
          theme: w