title: Drawer Quick Links
handle: drawer_quick_links
status: ready
variants:
  - name: Hub
    preview: '@hub'
  - name: Mini
    context:
      drawers:
        - title: 'Filter by title'
          variant: 'dr--sm'
          links:
            - name: Pay a parking ticket
            - name: Pay a parking ticket
            - name: Pay a parking ticket
  - name: JS Controlled
    context:
      drawers:
        - title: 'November 8, 2016: General Election'
          js: true
        - title: 'November 8, 20 16: General Election'
          js: true
          variant: 'dr--open'
          links:
            - name: Pay a parking ticket
              theme: w
context:
  drawers:
    - index: 1
      title: 'November 8, 2016: General Election'
      variant: 'dr--open'
      date: false
      theme: 'b'
      links:
        - name: Pay a parking ticket